### ISSUE TITLE
Kubernetes CRD controller for Application resources

### ISSUE THREAD

**Issue by yuji-watanabe-jp** [argoproj-labs/argocd-interlace#3]
Implement Kubernetes CRD controller for Application resources.
- monitors the trigger from state changes of Application resources
- detect new manifest build and captures desired manifests from ArgoCD REST API
- sign the manifest
- record the detail of manifest build 
   - the source files, git url, revision, commits for the manifest build
   - the command to produce the manifest for reproducibility. 
- store the details as provenance records in in-toto format.

**Comment by gajananan** [comment]
Now I am working on ArgoCD Interlace  [here](https://github.com/gajananan/argocd-interlace/tree/e2e_poc) .

An example of a generated provenance data by current implementation is like the following.

```
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "predicateType": "https://in-toto.io/Provenance/v0.1",
  "subject": [
    {
      "name": "gcr.io/kg-image-registry/akeme-signed-dev:1.0.0",
      "digest": {
        "sha256": "ad268fe3b2aec894f577d9b2b52c3404a6116d3ddf9a50546c11c68fb392633d"
      }
    }
  ],
  "predicate": {
    "builder": {
      "id": ""
    },
    "recipe": {
      "type": "",
      "entryPoint": "argocd-interlace",
      "arguments": ["-n argocd"]
    },
    "metadata": {
      "buildStartedOn": "2021-08-10T10:35:59.853833564Z",
      "buildFinishedOn": "2021-08-10T10:36:10.479247319Z",
      "completeness": {
        "arguments": false,
        "environment": false,
        "materials": false
      },
      "reproducible": true
    },
    "materials": [
      {
        "uri": "https://github.com/gajananan/akmebank-config",
        "digest": {
          "commit": "4cbb5158021547cb7bd9656752059abaf1b51916",
          "path": "roles/stage",
          "revision": "main"
        }
      }
    ]
  }
}
```

**Comment by gajananan** [comment]
Added capabilities (git storage), readme via a new PR: https://github.com/IBM/argocd-interlace/pull/7
